# Libraries required for tagging process

In [16]:
# libraries required

import spacy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
import pandas as pd
import matplotlib.pyplot as plt
import re

###  Data loading

In [17]:
data = pd.read_csv('bbc_news.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [18]:
titles = pd.DataFrame(data['title'])
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

## Data Cleaning

#### Lower case

In [19]:
titles['Lowercase'] = titles['title'].str.lower()
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   Lowercase  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

#### Remove stopwords

In [21]:
en_stopwords = stopwords.words('english')
print(en_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [22]:
titles['no_stopwords'] = titles['Lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))
titles.head()

,title,Lowercase,no_stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

#### Remove Punctuations

In [23]:
titles['no_punct'] = titles.apply(lambda x : re.sub(r'[^\w\s]', '', x['no_stopwords']), axis=1)
titles.head()

,title,Lowercase,no_stopwords,no_punct
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

#### Tokenization

In [28]:
titles['Tokens_raw'] = titles.apply(lambda x: word_tokenize(x['title']), axis=1)
titles['Tokens_clean'] = titles.apply(lambda x: word_tokenize(x['no_punct']), axis=1)
titles.head()

,title,Lowercase,no_stopwords,no_punct,Tokens_clean,Lemmatized_clean,Tokens_raw
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[refuse, work]","[Can, I, refuse, to, work, ?]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic...","['Liz, Truss, the, Brief, ?, ', World, reacts,..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com...","[Rationing, energy, is, nothing, new, for, off..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga...","[The, hunt, for, superyachts, of, sanctioned, ..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]","[Platinum, Jubilee, :, 70, years, of, the, Que..."

#### Lemmatization

In [29]:
lemmatizer = WordNetLemmatizer()
titles['Lemmatized_clean'] = titles['Tokens_clean'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
titles.head()

,title,Lowercase,no_stopwords,no_punct,Tokens_clean,Lemmatized_clean,Tokens_raw
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[refuse, work]","[Can, I, refuse, to, work, ?]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic...","['Liz, Truss, the, Brief, ?, ', World, reacts,..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com...","[Rationing, energy, is, nothing, new, for, off..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga...","[The, hunt, for, superyachts, of, sanctioned, ..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]","[Platinum, Jubilee, :, 70, years, of, the, Que..."

#### Tokens

In [31]:
tokens_raw_list = sum(titles['Tokens_raw'],[])
tokens_clean_list = sum(titles['Tokens_clean'],[])

print(tokens_raw_list)

['Can', 'I', 'refuse', 'to', 'work', '?', "'Liz", 'Truss', 'the', 'Brief', '?', "'", 'World', 'reacts', 'to', 'UK', 'political', 'turmoil', 'Rationing', 'energy', 'is', 'nothing', 'new', 'for', 'off-grid', 'community', 'The', 'hunt', 'for', 'superyachts', 'of', 'sanctioned', 'Russian', 'oligarchs', 'Platinum', 'Jubilee', ':', '70', 'years', 'of', 'the', 'Queen', 'in', '70', 'seconds', 'Red', 'Bull', 'found', 'guilty', 'of', 'breaking', 'Formula', '1', "'s", 'budget', 'cap', 'World', 'Triathlon', 'Championship', 'Series', ':', 'Flora', 'Duffy', 'beats', 'Georgia', 'Taylor-Brown', 'to', 'women', "'s", 'title', 'Terry', 'Hall', ':', 'Coventry', 'scooter', 'ride-out', 'pays', 'tribute', 'to', 'singer', 'Post', 'Office', 'and', 'Fujitsu', 'to', 'face', 'inquiry', 'over', 'Horizon', 'scandal', "'Pavement", 'parking', 'frightens', 'me', "'", 'UK', 'interest', 'rates', ':', 'How', 'will', 'the', 'rise', 'affect', 'you', 'and', 'how', 'high', 'could', 'it', 'go', '?', 'They', 'stayed', 'for', 'the', 'storm', '-', 'what', 'happens', 'now', '?', 'Six', 'Nations', ':', 'Can', 'Scotland', "'s", 'best', 'since', "'99", 'beat', 'best', 'Ireland', 'ever', '?', 'How', 'long', 'can', 'Liz', 'Truss', 'survive', 'as', 'prime', 'minister', '?', 'Platinum', 'Jubilee', ':', 'Beacons', 'light', 'across', 'the', 'globe', 'to', 'celebrate', 'Queen', "'s", 'reign', 'Top', 'student', 'loan', 'interest', 'rate', 'cut', 'by', '5', '%', 'in', 'England', 'Russians', 'said', 'they', '’', 'd', 'take', 'my', 'baby', ':', 'A', 'medic', '’', 's', 'story', 'Week', 'in', 'pictures', ':', '11-17', 'June', '2022', 'Xi', 'Jinping', 'in', 'Hong', 'Kong', ':', 'Tight', 'security', 'as', 'city', 'marks', '25', 'years', 'of', 'handover', 'Rescues', 'carried', 'out', 'in', 'silence', 'to', 'listen', 'for', 'sounds', 'of', 'life', 'Nick', 'Pope', ':', 'Newcastle', 'goalkeeper', 'extends', 'incredible', 'clean', 'sheet', 'record', 'How', 'China', 'plans', 'to', 'become', 'the', 'next', 'big', 'space', 'power', 'Barcelona', 'thrash', 'leaders', 'Real', 'Madrid', 'in', 'famous', 'Clasico', 'win', 'Kuenssberg', ':', 'The', 'Budget', 'can', 'not', 'mask', 'big', 'changes', 'to', 'our', 'economy', 'Nicola', 'Bulley', 'search', ':', 'What', 'we', 'know', 'about', 'her', 'disappearance', 'Cost', 'of', 'living', ':', 'Can', 'Christmas', 'lights', 'displays', 'survive', 'the', 'energy', 'crisis', '?', 'The', '100-year-old', 'Edinburgh', 'man', 'still', 'working', 'three', 'days', 'a', 'week', 'Freya', 'the', '600kg', 'walrus', 'causes', 'a', 'stir', 'in', 'Norway', 'How', 'can', 'I', 'offer', 'a', 'UK', 'home', 'to', 'Ukrainian', 'refugees', '?', 'Nicola', 'Bulley', 'search', ':', 'Former', 'police', 'boss', 'says', 'criticism', 'is', 'unfair', 'Don', 'Bolduc', ':', 'Democrats', 'elevated', 'this', 'Republican', '.', 'Will', 'it', 'backfire', '?', 'Some', 'strike', 'action', 'cancelled', 'after', 'the', 'Queen', "'s", 'death', 'The', 'neighbourhood', 'leading', 'a', 'green', 'energy', 'revolution', 'Men', "'s", 'U17', 'European', 'Championship', ':', 'Dutch', '17-year-old', 'Isaac', 'Babadi', 'scores', 'Panenka', 'penalty', 'Amtrak', 'derailment', ':', 'Three', 'killed', 'in', 'Missouri', 'after', 'train', 'hits', 'truck', 'Energy', 'price', 'cap', ':', 'Rising', 'bills', '-', 'four', 'discounts', 'and', 'payments', 'that', 'could', 'help', 'you', 'Environment', ':', 'Are', 'mushroom', 'boards', 'the', 'future', 'of', 'surfing', '?', 'Flying', 'boats', 'and', 'other', 'tech', 'for', 'cleaner', 'shipping', 'Scottish', 'football', 'to', 'ban', 'heading', 'the', 'day', 'before', 'and', 'after', 'matches', 'Chris', 'Eubank', 'Jr', 'v', 'Liam', 'Smith', ':', 'What', 'next', 'for', 'boxing', 'after', "'unacceptable", "'", 'taunts', '?', 'The', 'town', 'destroyed', 'to', 'make', 'way', 'for', 'a', 'whites-only', 'suburb', 'Ukraine', 'war', ':', 'A', 'village', 'celebrates', 'Russian', 'retreat', 'Root', 'hits', 'ton', 'as', 'England', 'take', 'command', 'against', 'West', 'Indies', 'Heineken', 'Champions', 'Cup', ':', 'Leicester', '16-6', 'Edinburgh', '-', 'Jasper', 'Wiese', 'try', 'sends', 'Tigers', 'into', 'last', 'eight', 'World', 'Cup', '2022', ':', 'Bellingham', ',', 'Gakpo', ',', 'Fernandez', 'and', 'other', 'breakout', 'stars', 'Briton', 'Jack', 'Fenton', 'killed', 'in', 'Greek', 'helicopter', 'accident', 'Emotional', 'Sue', 'Barker', 'gets', 'Centre', 'Court', 'ovation', 'Ukrainian', 'skating', 'sisters', 'back', 'to', "'doing", 'what', 'they', 'love', "'", 'England', 'v', 'India', ':', 'Edgbaston', 'officials', 'investigate', 'crowd', 'racism', 'at', 'Test', 'Newspaper', 'headlines', ':', 'Rwanda', 'plan', "'will", 'fail', "'", 'and', "'SAS", 'train', 'Kyiv', 'forces', "'", 'My', 'Name', 'Is', 'Leon', ':', 'Sir', 'Lenny', 'Henry', 'brings', "'moving", "'", 'adoption', 'story', 'to', 'screen', 'Big', 'Brother', 'star', 'Glyn', 'Wise', 'plans', 'to', 'be', 'priest', 'Ministers', 'asleep', 'at', 'the', 'wheel', 'over', 'dentist', 'shortages', ',', 'say', 'Lib', 'Dems', 'Chris', 'Kaba', ':', 'Met', 'suspends', 'officer', 'who', 'shot', 'dead', 'unarmed', 'man', 'World', 'Cup', '2022', ':', 'What', 'we', 'learned', 'from', 'a', 'group', 'stage', 'that', 'saw', 'record', 'number', 'of', 'upsets', 'James', 'Webb', ':', 'Nasa', 'space', 'telescope', 'delivers', 'spectacular', 'pictures', 'Constitution', 'Hill', ':', 'Cheltenham', 'Champion', 'Hurdle', 'winner', "'the", 'horse', 'of', 'a', 'generation', "'", 'At', 'least', 'one', 'victim', 'could', 'have', 'survived', 'arena', 'bomb', '-', 'inquiry', 'Gareth', 'Bale', ':', 'Wales', 'captain', 'retires', 'from', 'football', 'aged', '33', 'Ukraine', 'war', ':', 'Silent', 'streets', 'in', 'wiped', 'out', 'Donetsk', 'town', 'World', 'Cup', '2022', ':', 'Vittorio', 'Pozzo', "'s", 'legacy', 'and', 'a', 'record', 'that', 'might', 'finally', 'be', 'under', 'threat', 'Train', 'strikes', ':', 'Workers', 'vote', 'on', 'further', 'six', 'months', 'of', 'walkouts', 'Eidevall', "'100", '%', 'sure', "'", 'Arsenal', 'will', 'advance', 'after', 'first-leg', 'draw', 'Ukraine', 'war', ':', 'Returning', 'to', 'the', 'place', 'my', 'father', 'was', 'killed', 'Furniture', 'firm', 'Made', 'collapse', ':', 'Customers', 'in', 'the', 'dark', 'over', 'refunds', 'Widow', 'of', 'US', 'Capitol', 'riot', 'officer', 'on', "'stigma", "'", 'of', 'his', 'death', 'NHS', 'reaches', 'deal', 'for', 'life-saving', 'breast-cancer', 'drug', 'Giant', 'ceramic', 'sculpture', 'by', 'Sandy', 'Brown', 'has', 'been', 'unveiled', 'in', 'Cornwall', 'CEO', 'Secrets', ':', 'How', 'one', 'company', 'attracts', 'more', 'men', 'Boris', 'Becker', ':', 'How', 'a', 'tennis', 'superstar', 'crashed', 'to', 'earth', 'Turkish', 'mine', 'explosion', 'kills', '25', 'and', 'leaves', 'dozens', 'trapped', 'Indian', 'Wells', ':', 'Andy', 'Murray', ',', 'Emma', 'Raducanu', 'and', 'Jack', 'Draper', 'win', 'to', 'reach', 'third', 'round', 'World', 'Athletics', 'Championships', ':', 'GB', "'s", 'Keely', 'Hodgkinson', 'narrowly', 'misses', 'out', 'on', 'gold', 'in', 'dramatic', '800m', 'NHS', 'crisis', ':', 'The', 'medics', 'trying', 'to', 'fix', 'the', 'health', 'service', 'How', 'did', 'jet', 'crash', 'into', 'a', 'block', 'of', 'flats', 'in', 'Russia', '?', 'Prince', 'Harry', 'and', 'Meghan', ':', 'Where', 'do', 'they', 'get', 'their', 'money', '?', 'Chelsea', '4-2', 'Man', 'Utd', ':', 'Chelsea', 'win', 'historic', 'third', 'successive', 'WSL', 'title', 'Tory', 'leadership', ':', 'I', "'d", 'rather', 'lose', 'doing', 'right', 'thing', ',', 'says', 'Sunak', 'Omagh', 'police', 'shooting', ':', 'Four', 'men', 'released', 'over', 'John', 'Caldwell', 'attack', 'Northern', 'Ireland', '1-0', 'Italy', ':', 'Sarah', 'McFadden', 'scores', 'famous', 'winner', 'in', 'Belfast', 'Actress', 'Clara', 'Darcy', ':', 'Why', 'I', "'m", 'starring', 'in', 'a', 'play', 'about', 'my', 'brain', 'tumour', 'Bridgerton', ':', 'South', 'Asian', 'faces', 'on', 'TV', "'makes", 'me', 'happy', "'", 'Prince', 'Harry', 'remembers', 'Queen', 'Elizabeth', 'II', "'s", 'infectious', 'smile', 'Millions', 'to', 'receive', 'latest', 'cost-of-living', 'payment', 'Joe', 'Biden', 'heads', 'to', 'Middle', 'East', 'amid', 'faltering', 'US', 'sway', 'NHS', ':', 'Public', 'satisfaction', 'with', 'health', 'service', 'drops', 'to', 'record', 'low', 'Why', 'have', "n't", 'we', 'seen', 'any', 'major', 'winter', 'storms', '?', 'The', 'Papers', ':', 'Lions', "'bare", 'teeth', "'", 'and', 'Starmer', "'s", 'migration', 'policy', 'Afghanistan', 'pupils', 'in', 'fear', 'after', 'spate', 'of', 'Islamic', 'State', 'attacks', 'Princess', 'of', 'Wales', 'Kate', 'pays', 'tribute', 'to', 'Queen', 'Elizabeth', 'at', 'carol', 'service', 'Emma', 'Raducanu', ':', 'US', 'Open', 'champion', 'discusses', "'tough", "'", 'split', 'with', 'coach', 'Torben', 'Beltz', 'Oxford', 'United', '0-3', 'Arsenal', ':', 'Eddie', 'Nketiah', 'scores', 'twice', 'as', 'Gunners', 'progress', 'Ukraine', 'round-up', ':', 'Putin', 'defends', "'necessary", "'", 'invasion', 'and', 'Kyiv', 'averts', 'cyber-attack', 'NI', 'Protocol', ':', 'UK', 'and', 'EU', 'reach', 'agreement', 'on', 'trade', 'data', 'sharing', 'Super', 'Mario', 'Bros.', 'movie', ':', 'Jack', 'Black', 'on', 'the', 'rise', 'of', 'game', 'adaptations', 'Four-time', 'Slam', 'champion', 'Osaka', 'announces', 'pregnancy', 'McDonald', "'s", 'and', 'Coca-Cola', 'boycott', 'calls', 'grow', 'over', 'Russia', 'Women', "'s", 'Footballer', 'of', 'the', 'Year', 'contender', 'Sam', 'Kerr', 'War', 'in', 'Ukraine', ':', 'Why', 'Vladimir', 'Putin', 'could', "n't", 'have', 'trained', 'fighters', 'in', 'Africa', 'Ryanair', "'s", 'Michael', "O'Leary", 'wants', "'practical", "'", 'immigration', 'approach', "'", 'I', 'planned', 'to', 'end', 'my', 'life', 'at', '16', 'but', 'I', "'m", 'still', 'here', "'", 'How', 'England', "'s", '14', 'men', 'whipped', 'up', 'Twickenham', 'crowd', 'with', 'stirring', 'display', 'The', 'Open', ':', 'Rory', 'McIlroy', 'and', 'Viktor', 'Hovland', 'share', 'lead', 'at', 'St', 'Andrews', 'after', 'third', 'round', 'Real', 'Madrid', '2-0', 'Eintracht', 'Frankfurt', ':', 'Karim', 'Benzema', 'scores', '324th', 'goal', 'for', 'Real', 'in', 'Super', 'Cup', 'win', 'The', 'Papers', ':', 'Boris', 'dossier', 'and', 'judges', "'to", 'back', 'down', "'", 'on', 'Rwanda', 'Queen', 'pulls', 'out', 'of', 'attending', 'Commonwealth', 'Service', 'Mosque', 'fire', 'suspect', 'arrested', 'over', 'second', 'attack', 'World', 'Cup', '2022', ':', 'Belgium', 'to', 'drop', "'love", "'", 'from', 'away', 'shirts', 'in', 'Qatar', 'What', 'are', 'the', 'UK', "'s", 'Living', 'with', 'Covid', 'plans', '?', 'Soho', "'s", 'streets', 'turned', 'into', 'new', 'London', 'art', 'gallery', 'The', 'Papers', ':', "'Cruise", 'ships', "'", 'to', 'house', 'migrants', 'and', 'new', 'NHS', 'cash', 'Pay', 'gap', 'from', 'bosses', 'to', 'staff', 'to', 'widen', '-', 'think', 'tank', 'Local', 'elections', ':', 'Children', 'urge', 'action', 'to', 'save', 'wildlife', 'Climate', 'change', ':', 'Is', 'the', 'UK', 'on', 'track', 'to', 'meet', 'its', 'targets', '?', 'Trump', 'investigation', ':', 'Empty', 'folders', 'marked', 'classified', 'found', 'at', 'Mar-a-Lago', 'Jim', 'Ratcliffe', ':', 'Who', 'is', 'the', 'man', 'bidding', 'for', 'Man', 'Utd', '?', 'Shropshire', 'baby', 'deaths', ':', 'The', 'parents', 'whose', 'lives', 'were', 'changed', 'forever', 'More', 'bus', 'journeys', 'taken', 'since', '£2', 'fare', 'cap', ',', 'says', 'watchdog', 'Mexico', 'kidnapping', ':', 'A', 'twisted', 'moral', 'code', 'explains', 'cartel', "'s", 'apology', 'Rail', 'fares', 'in', 'England', 'to', 'rise', 'below', 'inflation', 'rate', ',', 'ministers', 'say', 'Taliban', 'schools', 'U-turn', "'", 'a', 'devastating', 'day', "'", 'for', 'Afghan', 'girls', '-', 'Malala', 'Yousafzai', 'Met', 'Police', ':', 'Where', 'next', 'for', 'the', 'force', 'after', 'Casey', 'review', '?', 'Ukraine', 'war', ':', 'Why', 'Kherson', 'and', 'Mariupol', 'are', 'key', 'to', 'Russian', 'success', 'Heineken', 'Champions', 'Cup', ':', 'Premiership', 'cap', 'hinders', 'English', 'teams', '-', 'Alex', 'Sanderson', 'Ukraine', 'war', ':', 'Protester', 'exposes', 'cracks', 'in', 'Kremlin', "'s", 'war', 'message', 'Liz', 'Truss', 'vows', 'to', 'match', 'Ukraine', 'military', 'support', 'as', 'politics', 'returns', 'Wales', "'", 'population', 'hits', 'new', 'high', 'but', 'growth', 'is', 'lowest', 'How', 'many', 'Ukrainians', 'have', 'fled', 'their', 'homes', 'and', 'where', 'have', 'they', 'gone', '?', 'Deloitte', 'report', ':', 'European', 'football', 'has', 'made', "'significant", 'recovery', "'", 'after', 'Covid', 'pandemic', 'Nigeria', 'floods', ':', "'Overwhelming", "'", 'disaster', 'leaves', 'more', 'than', '600', 'people', 'dead', 'Wimbledon', ':', 'Emma', 'Raducanu', '&', 'Andy', 'Murray', 'set', 'for', 'Centre', 'Court', 'on', 'day', 'one', 'A', 'journey', 'to', 'the', 'site', 'of', 'the', 'Nord', 'Stream', 'explosions', 'Quiz', 'of', 'the', 'week', ':', 'Why', 'was', 'Lindsay', 'Lohan', 'in', 'trouble', '?', 'Gracie', 'Spinks', ':', 'Receipt', 'could', 'have', 'traced', 'killer', '-', 'family', 'Supreme', 'Court', ':', 'What', 'happens', 'if', 'Roe', 'v', 'Wade', 'overturned', '?', 'Chancellor', 'warns', 'of', 'tax', 'rises', 'and', 'squeeze', 'on', 'spending', 'Imran', 'Khan', 'ousted', 'as', 'Pakistan', "'s", 'PM', 'after', 'key', 'vote', 'Artemis', ':', 'Nasa', "'s", 'Orion', 'capsule', 'breaks', 'distance', 'record', 'How', 'Ukraine', 'is', 'winning', 'the', 'social', 'media', 'war', 'Flint', ':', 'Arrest', 'as', 'missing', 'girl', ',', '12', ',', 'found', 'in', 'Birmingham', 'France', 'drought', ':', 'Parched', 'towns', 'left', 'short', 'of', 'drinking', 'water', 'Invergordon', 'shed', 'door', 'marble', 'bust', 'could', 'be', 'sold', "'Massive", 'toll', "'", 'of', 'living', 'in', 'a', 'leasehold', 'property', 'Ukraine', 'war', ':', 'Put', 'values', 'over', 'profits', ',', 'Nato', 'chief', 'tells', 'countries', 'Buyers', 'revive', 'interest', 'in', 'city', 'flats', 'after', 'return', 'to', 'office', 'UK', 'weather', ':', 'How', 'long', 'will', 'the', 'cold', 'snap', 'last', '?', 'Hidilyn', 'Diaz', ':', 'From', 'accusations', 'of', 'anti-government', 'plot', 'to', 'historic', 'Olympic', 'gold', 'Government', 'to', 'introduce', 'independent', 'football', 'regulator', 'in', 'England', 'after', 'backing', 'fan-led', 'review', 'Pints', ',', 'power', 'and', 'parents', ':', 'Three', 'ways', 'the', 'Budget', 'could', 'affect', 'you', 'A-level', 'and', 'GCSE', 'exams', ':', 'What', 'happens', 'to', 'your', 'papers', '?', 'Is', 'Nato', "'s", 'Nordic', 'expansion', 'a', 'threat', 'or', 'boost', 'to', 'Europe', '?', 'Sudden', 'unknown', 'death', 'in', 'childhood', ':', "'Why", 'did', 'my', 'beautiful', 'son', 'die', '?', "'", 'Droylsden', ':', 'Man', 'charged', 'after', 'girl', ',', '6', ',', 'abducted', 'and', 'sexually', 'assaulted', 'FA', 'Cup', ':', 'Wrexham', '3-3', 'Sheffield', 'United', '-', 'Egan', "'s", 'late', 'strike', 'denies', 'Wrexham', 'victory', 'UK', 'is', 'compassionate', ',', 'says', 'PM', 'after', 'Suella', 'Braverman', 'invasion', 'row', 'Foreign', 'Secretary', 'Liz', 'Truss', 'joins', 'Tory', 'leadership', 'race', 'World', 'Cup', '2022', ':', 'Wales', 'must', "'put", 'big', 'boy', 'pants', 'on', "'", 'against', 'England', ',', 'says', 'boss', 'Robert', 'Page', 'I', 'forgive', 'the', 'man', 'who', 'tried', 'to', 'murder', 'me', 'IS', 'announces', 'leader', "'s", 'death', 'and', 'names', 'replacement', 'Nurses', "'", 'strike', ':', 'How', 'much', 'do', 'you', 'know', 'about', 'their', 'pay', '?', 'Try', 'our', 'quiz', 'Rishi', 'Sunak', 'speaks', 'of', 'safety', 'fears', 'for', 'daughter', 'Leslie', 'Jordan', ':', 'Will', 'and', 'Grace', 'star', 'dies', 'aged', '67', 'Olivia', 'Pratt-Korbel', 'murder-accused', 'was', "'high-level", "'", 'drug', 'dealer', 'North', 'Carolina', ':', 'Suspect,15', ',', 'in', 'custody', 'after', 'Raleigh', 'shooting', 'spree', 'UK', 'weather', ':', 'How', 'long', 'will', 'the', 'cold', 'snap', 'last', '?', 'Queen', "'s", 'funeral', 'guests', ':', 'Who', 'will', '-', 'and', 'who', 'wo', "n't", '-', 'attend', 'Rishi', 'Sunak', "'s", 'failure', 'to', 'wear', 'seat', 'belt', 'to', 'be', 'investigated', 'Heathrow', 'Airport', 'extends', 'cap', 'on', 'passengers', 'to', 'end', 'of', 'October', 'John', 'Peel', "'s", 'family', 'selling', 'rare', 'items', 'from', 'his', 'archive', 'MPs', 'call', 'for', 'UK', 'ban', 'on', 'two', 'Chinese', 'CCTV', 'firms', 'US', 'economy', 'shrinks', 'again', 'sparking', 'recession', 'fears', 'Women', "'s", 'T20', 'World', 'Cup', ':', 'England', 'and', 'India', 'prepare', 'for', 'decisive', 'group', 'stage', 'encounter', 'Michaela', 'McAreavey', ':', 'Two', 'men', 'apologise', 'for', 'video', 'mocking', 'bride', "'s", 'murder', 'Scotland', '2-1', 'Republic', 'of', 'Ireland', ':', 'Ryan', 'Christie', "'s", 'late', 'penalty', 'gives', 'hosts', 'crucial', 'win', 'How', 'much', 'could', 'your', 'mortgage', 'rise', '?', 'Try', 'our', 'calculator', 'Covid', 'vaccines', 'not', 'linked', 'to', 'deaths', ',', 'major', 'US', 'study', 'finds', 'Oscars', '2023', ':', 'RRR', "'s", 'Naatu', 'Naatu', 'wins', 'best', 'original', 'song', 'The', 'Papers', ':', 'Russia', 'accused', 'of', 'genocide', ',', 'and', "'fuel", 'duty', 'cut', "'", 'Forest', 'set', 'new', 'record', 'after', 'transfer-window', 'rush', 'WATCH', ':', 'Russian', 'tanks', 'abandoned', 'on', 'retaken', 'Ukrainian', 'territory', 'Could', 'the', 'Elgin', 'Marbles', 'be', 'returned', 'to', 'Greece', '?', 'Review', 'into', 'Nottingham', 'NHS', 'maternity', 'failings', 'launches', 'World', 'Cup', '2022', ':', 'Some', 'fans', 'miss', 'kick-off', 'after', 'Fifa', 'ticket', 'app', 'issues', 'England', 'U21s', '3-0', 'Albania', 'U21s', ':', 'Young', 'Lions', 'qualify', 'for', '2023', 'European', 'Under-21', 'Championship', 'How', 'to', 'make', 'movies', 'without', 'a', 'huge', 'carbon', 'footprint', 'TV', 'presenter', 'Matthew', 'Bassett', 'shows', 'life', 'goes', 'on', 'with', 'spinal', 'injury', 'GTA', ':', 'Rockstar', 'rejected', 'Eminem', 'movie', 'deal', ',', 'says', 'insider', 'World', 'Cup', '2022', ':', 'France', "'s", 'Kylian', 'Mbappe', 'upstages', 'Olivier', 'Giroud', 'after', 'goalscoring', 'record', 'The', 'mystery', 'deaths', 'of', 'two', 'Saudi', 'sisters', 'in', 'Sydney', 'Matt', 'Hancock', 'on', 'I', "'m", 'A', 'Celebrity', 'led', 'to', 'dozens', 'of', 'complaints', 'to', 'MPs', "'", 'watchdog', 'Cricket', 'World', 'Cup', ':', 'England-Australia', 'final', 'to', 'be', 'shown', 'free', 'to', 'air', 'on', 'Sunday', 'Nurses', 'strike', ':', 'Thousands', 'join', 'first', 'walkout', 'on', "'sad", 'day', "'", 'Exeter', ':', 'Man', 'held', 'over', 'murder', 'of', 'woman', 'in', 'Ludwell', 'Valley', 'Park', 'Tory', 'leadership', ':', 'Truss', 'criticised', 'for', 'Macron', "'jury", 'is', 'out', "'", 'remark', 'Is', 'Keir', 'Starmer', 'right', 'that', 'wages', 'have', 'been', "'stuck", 'for', 'a', 'decade', "'", '?', "'We", "'re", 'all', 'behind', 'you', "'", ':', 'Famous', 'faces', 'cheer', 'Lionesses', 'Zelensky', 'asked', 'if', 'he', "'ll", 'give', 'Russia', 'any', 'part', 'of', 'Ukraine', 'Amber', 'Heard', ':', 'It', "'s", 'easy', 'to', 'forget', 'I', "'m", 'a', 'human', 'being', 'Workers', 'take', 'to', 'London', "'s", 'streets', 'amid', 'cost', 'of', 'living', 'crisis', "'My", 'cancerous', 'tumour', 'was', 'as', 'big', 'as', 'a', 'kettle', 'bell', "'", 'Chester', 'Zoo', ':', 'Rare', 'baby', 'wallaby', 'emerges', 'from', 'mother', "'s", 'pouch', 'World', 'Cup', '2022', ':', 'Belgium', 'were', "'afraid", 'to', 'lose', "'", 'against', 'Morocco', ',', 'says', 'Roberto', 'Martinez', 'Boy', 'George', "'s", 'tears', 'as', 'Hancock', 'enters', 'I', "'m", 'a', 'Celeb', 'camp', 'Elon', 'Musk', 'defends', 'racist', 'tirade', 'by', 'Dilbert', 'creator', 'Scott', 'Adams', 'How', 'Henry', 'the', 'cat', 'won', 'the', 'hearts', 'of', 'Addenbrooke', "'s", 'Hospital', 'Week', 'in', 'pictures', ':', '2', '-', '8', 'April', '2022', 'Former', 'UK', 'PM', 'Boris', 'Johnson', 'makes', 'trip', 'to', 'Ukraine', 

In [32]:
print(tokens_clean_list)

['refuse', 'work', 'liz', 'truss', 'brief', 'world', 'reacts', 'uk', 'political', 'turmoil', 'rationing', 'energy', 'nothing', 'new', 'offgrid', 'community', 'hunt', 'superyachts', 'sanctioned', 'russian', 'oligarchs', 'platinum', 'jubilee', '70', 'years', 'queen', '70', 'seconds', 'red', 'bull', 'found', 'guilty', 'breaking', 'formula', '1s', 'budget', 'cap', 'world', 'triathlon', 'championship', 'series', 'flora', 'duffy', 'beats', 'georgia', 'taylorbrown', 'womens', 'title', 'terry', 'hall', 'coventry', 'scooter', 'rideout', 'pays', 'tribute', 'singer', 'post', 'office', 'fujitsu', 'face', 'inquiry', 'horizon', 'scandal', 'pavement', 'parking', 'frightens', 'me', 'uk', 'interest', 'rates', 'rise', 'affect', 'high', 'could', 'go', 'stayed', 'storm', 'happens', 'now', 'six', 'nations', 'scotlands', 'best', 'since', '99', 'beat', 'best', 'ireland', 'ever', 'long', 'liz', 'truss', 'survive', 'prime', 'minister', 'platinum', 'jubilee', 'beacons', 'light', 'across', 'globe', 'celebrate', 'queens', 'reign', 'top', 'student', 'loan', 'interest', 'rate', 'cut', '5', 'england', 'russians', 'said', 'theyd', 'take', 'baby', 'medics', 'story', 'week', 'pictures', '1117', 'june', '2022', 'xi', 'jinping', 'hong', 'kong', 'tight', 'security', 'city', 'marks', '25', 'years', 'handover', 'rescues', 'carried', 'silence', 'listen', 'sounds', 'life', 'nick', 'pope', 'newcastle', 'goalkeeper', 'extends', 'incredible', 'clean', 'sheet', 'record', 'china', 'plans', 'become', 'next', 'big', 'space', 'power', 'barcelona', 'thrash', 'leaders', 'real', 'madrid', 'famous', 'clasico', 'win', 'kuenssberg', 'budget', 'can', 'not', 'mask', 'big', 'changes', 'economy', 'nicola', 'bulley', 'search', 'know', 'disappearance', 'cost', 'living', 'christmas', 'lights', 'displays', 'survive', 'energy', 'crisis', '100yearold', 'edinburgh', 'man', 'still', 'working', 'three', 'days', 'week', 'freya', '600kg', 'walrus', 'causes', 'stir', 'norway', 'offer', 'uk', 'home', 'ukrainian', 'refugees', 'nicola', 'bulley', 'search', 'former', 'police', 'boss', 'says', 'criticism', 'unfair', 'bolduc', 'democrats', 'elevated', 'republican', 'backfire', 'strike', 'action', 'cancelled', 'queens', 'death', 'neighbourhood', 'leading', 'green', 'energy', 'revolution', 'mens', 'u17', 'european', 'championship', 'dutch', '17yearold', 'isaac', 'babadi', 'scores', 'panenka', 'penalty', 'amtrak', 'derailment', 'three', 'killed', 'missouri', 'train', 'hits', 'truck', 'energy', 'price', 'cap', 'rising', 'bills', 'four', 'discounts', 'payments', 'could', 'help', 'environment', 'mushroom', 'boards', 'future', 'surfing', 'flying', 'boats', 'tech', 'cleaner', 'shipping', 'scottish', 'football', 'ban', 'heading', 'day', 'matches', 'chris', 'eubank', 'jr', 'v', 'liam', 'smith', 'next', 'boxing', 'unacceptable', 'taunts', 'town', 'destroyed', 'make', 'way', 'whitesonly', 'suburb', 'ukraine', 'war', 'village', 'celebrates', 'russian', 'retreat', 'root', 'hits', 'ton', 'england', 'take', 'command', 'west', 'indies', 'heineken', 'champions', 'cup', 'leicester', '166', 'edinburgh', 'jasper', 'wiese', 'try', 'sends', 'tigers', 'last', 'eight', 'world', 'cup', '2022', 'bellingham', 'gakpo', 'fernandez', 'breakout', 'stars', 'briton', 'jack', 'fenton', 'killed', 'greek', 'helicopter', 'accident', 'emotional', 'sue', 'barker', 'gets', 'centre', 'court', 'ovation', 'ukrainian', 'skating', 'sisters', 'back', 'doing', 'love', 'england', 'v', 'india', 'edgbaston', 'officials', 'investigate', 'crowd', 'racism', 'test', 'newspaper', 'headlines', 'rwanda', 'plan', 'will', 'fail', 'sas', 'train', 'kyiv', 'forces', 'name', 'leon', 'sir', 'lenny', 'henry', 'brings', 'moving', 'adoption', 'story', 'screen', 'big', 'brother', 'star', 'glyn', 'wise', 'plans', 'priest', 'ministers', 'asleep', 'wheel', 'dentist', 'shortages', 'say', 'lib', 'dems', 'chris', 'kaba', 'met', 'suspends', 'officer', 'shot', 'dead', 'unarmed', 'man', 'world', 'cup', '2022', 'learned', 'group', 'stage', 'saw', 'record', 'number', 'upsets', 'james', 'webb', 'nasa', 'space', 'telescope', 'delivers', 'spectacular', 'pictures', 'constitution', 'hill', 'cheltenham', 'champion', 'hurdle', 'winner', 'the', 'horse', 'generation', 'least', 'one', 'victim', 'could', 'survived', 'arena', 'bomb', 'inquiry', 'gareth', 'bale', 'wales', 'captain', 'retires', 'football', 'aged', '33', 'ukraine', 'war', 'silent', 'streets', 'wiped', 'donetsk', 'town', 'world', 'cup', '2022', 'vittorio', 'pozzos', 'legacy', 'record', 'might', 'finally', 'threat', 'train', 'strikes', 'workers', 'vote', 'six', 'months', 'walkouts', 'eidevall', '100', 'sure', 'arsenal', 'advance', 'firstleg', 'draw', 'ukraine', 'war', 'returning', 'place', 'father', 'killed', 'furniture', 'firm', 'made', 'collapse', 'customers', 'dark', 'refunds', 'widow', 'us', 'capitol', 'riot', 'officer', 'stigma', 'death', 'nhs', 'reaches', 'deal', 'lifesaving', 'breastcancer', 'drug', 'giant', 'ceramic', 'sculpture', 'sandy', 'brown', 'unveiled', 'cornwall', 'ceo', 'secrets', 'one', 'company', 'attracts', 'men', 'boris', 'becker', 'tennis', 'superstar', 'crashed', 'earth', 'turkish', 'mine', 'explosion', 'kills', '25', 'leaves', 'dozens', 'trapped', 'indian', 'wells', 'andy', 'murray', 'emma', 'raducanu', 'jack', 'draper', 'win', 'reach', 'third', 'round', 'world', 'athletics', 'championships', 'gbs', 'keely', 'hodgkinson', 'narrowly', 'misses', 'gold', 'dramatic', '800m', 'nhs', 'crisis', 'medics', 'trying', 'fix', 'health', 'service', 'jet', 'crash', 'block', 'flats', 'russia', 'prince', 'harry', 'meghan', 'get', 'money', 'chelsea', '42', 'man', 'utd', 'chelsea', 'win', 'historic', 'third', 'successive', 'wsl', 'title', 'tory', 'leadership', 'rather', 'lose', 'right', 'thing', 'says', 'sunak', 'omagh', 'police', 'shooting', 'four', 'men', 'released', 'john', 'caldwell', 'attack', 'northern', 'ireland', '10', 'italy', 'sarah', 'mcfadden', 'scores', 'famous', 'winner', 'belfast', 'actress', 'clara', 'darcy', 'starring', 'play', 'brain', 'tumour', 'bridgerton', 'south', 'asian', 'faces', 'tv', 'makes', 'happy', 'prince', 'harry', 'remembers', 'queen', 'elizabeth', 'iis', 'infectious', 'smile', 'millions', 'receive', 'latest', 'costofliving', 'payment', 'joe', 'biden', 'heads', 'middle', 'east', 'amid', 'faltering', 'us', 'sway', 'nhs', 'public', 'satisfaction', 'health', 'service', 'drops', 'record', 'low', 'seen', 'major', 'winter', 'storms', 'papers', 'lions', 'bare', 'teeth', 'starmers', 'migration', 'policy', 'afghanistan', 'pupils', 'fear', 'spate', 'islamic', 'state', 'attacks', 'princess', 'wales', 'kate', 'pays', 'tribute', 'queen', 'elizabeth', 'carol', 'service', 'emma', 'raducanu', 'us', 'open', 'champion', 'discusses', 'tough', 'split', 'coach', 'torben', 'beltz', 'oxford', 'united', '03', 'arsenal', 'eddie', 'nketiah', 'scores', 'twice', 'gunners', 'progress', 'ukraine', 'roundup', 'putin', 'defends', 'necessary', 'invasion', 'kyiv', 'averts', 'cyberattack', 'ni', 'protocol', 'uk', 'eu', 'reach', 'agreement', 'trade', 'data', 'sharing', 'super', 'mario', 'bros', 'movie', 'jack', 'black', 'rise', 'game', 'adaptations', 'fourtime', 'slam', 'champion', 'osaka', 'announces', 'pregnancy', 'mcdonalds', 'cocacola', 'boycott', 'calls', 'grow', 'russia', 'womens', 'footballer', 'year', 'contender', 'sam', 'kerr', 'war', 'ukraine', 'vladimir', 'putin', 'trained', 'fighters', 'africa', 'ryanairs', 'michael', 'oleary', 'wants', 'practical', 'immigration', 'approach', 'i', 'planned', 'end', 'life', '16', 'still', 'here', 'englands', '14', 'men', 'whipped', 'twickenham', 'crowd', 'stirring', 'display', 'open', 'rory', 'mcilroy', 'viktor', 'hovland', 'share', 'lead', 'st', 'andrews', 'third', 'round', 'real', 'madrid', '20', 'eintracht', 'frankfurt', 'karim', 'benzema', 'scores', '324th', 'goal', 'real', 'super', 'cup', 'win', 'papers', 'boris', 'dossier', 'judges', 'to', 'back', 'down', 'rwanda', 'queen', 'pulls', 'attending', 'commonwealth', 'service', 'mosque', 'fire', 'suspect', 'arrested', 'second', 'attack', 'world', 'cup', '2022', 'belgium', 'drop', 'love', 'away', 'shirts', 'qatar', 'uks', 'living', 'covid', 'plans', 'sohos', 'streets', 'turned', 'new', 'london', 'art', 'gallery', 'papers', 'cruise', 'ships', 'house', 'migrants', 'new', 'nhs', 'cash', 'pay', 'gap', 'bosses', 'staff', 'widen', 'think', 'tank', 'local', 'elections', 'children', 'urge', 'action', 'save', 'wildlife', 'climate', 'change', 'uk', 'track', 'meet', 'targets', 'trump', 'investigation', 'empty', 'folders', 'marked', 'classified', 'found', 'maralago', 'jim', 'ratcliffe', 'man', 'bidding', 'man', 'utd', 'shropshire', 'baby', 'deaths', 'parents', 'whose', 'lives', 'changed', 'forever', 'bus', 'journeys', 'taken', 'since', '2', 'fare', 'cap', 'says', 'watchdog', 'mexico', 'kidnapping', 'twisted', 'moral', 'code', 'explains', 'cartels', 'apology', 'rail', 'fares', 'england', 'rise', 'inflation', 'rate', 'ministers', 'say', 'taliban', 'schools', 'uturn', 'a', 'devastating', 'day', 'afghan', 'girls', 'malala', 'yousafzai', 'met', 'police', 'next', 'force', 'casey', 'review', 'ukraine', 'war', 'kherson', 'mariupol', 'key', 'russian', 'success', 'heineken', 'champions', 'cup', 'premiership', 'cap', 'hinders', 'english', 'teams', 'alex', 'sanderson', 'ukraine', 'war', 'protester', 'exposes', 'cracks', 'kremlins', 'war', 'message', 'liz', 'truss', 'vows', 'match', 'ukraine', 'military', 'support', 'politics', 'returns', 'wales', 'population', 'hits', 'new', 'high', 'growth', 'lowest', 'many', 'ukrainians', 'fled', 'homes', 'gone', 'deloitte', 'report', 'european', 'football', 'made', 'significant', 'recovery', 'covid', 'pandemic', 'nigeria', 'floods', 'overwhelming', 'disaster', 'leaves', '600', 'people', 'dead', 'wimbledon', 'emma', 'raducanu', 'andy', 'murray', 'set', 'centre', 'court', 'day', 'one', 'journey', 'site', 'nord', 'stream', 'explosions', 'quiz', 'week', 'lindsay', 'lohan', 'trouble', 'gracie', 'spinks', 'receipt', 'could', 'traced', 'killer', 'family', 'supreme', 'court', 'happens', 'roe', 'v', 'wade', 'overturned', 'chancellor', 'warns', 'tax', 'rises', 'squeeze', 'spending', 'imran', 'khan', 'ousted', 'pakistans', 'pm', 'key', 'vote', 'artemis', 'nasas', 'orion', 'capsule', 'breaks', 'distance', 'record', 'ukraine', 'winning', 'social', 'media', 'war', 'flint', 'arrest', 'missing', 'girl', '12', 'found', 'birmingham', 'france', 'drought', 'parched', 'towns', 'left', 'short', 'drinking', 'water', 'invergordon', 'shed', 'door', 'marble', 'bust', 'could', 'sold', 'massive', 'toll', 'living', 'leasehold', 'property', 'ukraine', 'war', 'put', 'values', 'profits', 'nato', 'chief', 'tells', 'countries', 'buyers', 'revive', 'interest', 'city', 'flats', 'return', 'office', 'uk', 'weather', 'long', 'cold', 'snap', 'last', 'hidilyn', 'diaz', 'accusations', 'antigovernment', 'plot', 'historic', 'olympic', 'gold', 'government', 'introduce', 'independent', 'football', 'regulator', 'england', 'backing', 'fanled', 'review', 'pints', 'power', 'parents', 'three', 'ways', 'budget', 'could', 'affect', 'alevel', 'gcse', 'exams', 'happens', 'papers', 'natos', 'nordic', 'expansion', 'threat', 'boost', 'europe', 'sudden', 'unknown', 'death', 'childhood', 'why', 'beautiful', 'son', 'die', 'droylsden', 'man', 'charged', 'girl', '6', 'abducted', 'sexually', 'assaulted', 'fa', 'cup', 'wrexham', '33', 'sheffield', 'united', 'egans', 'late', 'strike', 'denies', 'wrexham', 'victory', 'uk', 'compassionate', 'says', 'pm', 'suella', 'braverman', 'invasion', 'row', 'foreign', 'secretary', 'liz', 'truss', 'joins', 'tory', 'leadership', 'race', 'world', 'cup', '2022', 'wales', 'must', 'put', 'big', 'boy', 'pants', 'on', 'england', 'says', 'boss', 'robert', 'page', 'forgive', 'man', 'tried', 'murder', 'announces', 'leaders', 'death', 'names', 'replacement', 'nurses', 'strike', 'much', 'know', 'pay', 'try', 'quiz', 'rishi', 'sunak', 'speaks', 'safety', 'fears', 'daughter', 'leslie', 'jordan', 'grace', 'star', 'dies', 'aged', '67', 'olivia', 'prattkorbel', 'murderaccused', 'highlevel', 'drug', 'dealer', 'north', 'carolina', 'suspect15', 'custody', 'raleigh', 'shooting', 'spree', 'uk', 'weather', 'long', 'cold', 'snap', 'last', 'queens', 'funeral', 'guests', 'attend', 'rishi', 'sunaks', 'failure', 'wear', 'seat', 'belt', 'investigated', 'heathrow', 'airport', 'extends', 'cap', 'passengers', 'end', 'october', 'john', 'peels', 'family', 'selling', 'rare', 'items', 'archive', 'mps', 'call', 'uk', 'ban', 'two', 'chinese', 'cctv', 'firms', 'us', 'economy', 'shrinks', 'sparking', 'recession', 'fears', 'womens', 't20', 'world', 'cup', 'england', 'india', 'prepare', 'decisive', 'group', 'stage', 'encounter', 'michaela', 'mcareavey', 'two', 'men', 'apologise', 'video', 'mocking', 'brides', 'murder', 'scotland', '21', 'republic', 'ireland', 'ryan', 'christies', 'late', 'penalty', 'gives', 'hosts', 'crucial', 'win', 'much', 'could', 'mortgage', 'rise', 'try', 'calculator', 'covid', 'vaccines', 'linked', 'deaths', 'major', 'us', 'study', 'finds', 'oscars', '2023', 'rrrs', 'naatu', 'naatu', 'wins', 'best', 'original', 'song', 'papers', 'russia', 'accused', 'genocide', 'fuel', 'duty', 'cut', 'forest', 'set', 'new', 'record', 'transferwindow', 'rush', 'watch', 'russian', 'tanks', 'abandoned', 'retaken', 'ukrainian', 'territory', 'could', 'elgin', 'marbles', 'returned', 'greece', 'review', 'nottingham', 'nhs', 'maternity', 'failings', 'launches', 'world', 'cup', '2022', 'fans', 'miss', 'kickoff', 'fifa', 'ticket', 'app', 'issues', 'england', 'u21s', '30', 'albania', 'u21s', 'young', 'lions', 'qualify', '2023', 'european', 'under21', 'championship', 'make', 'movies', 'without', 'huge', 'carbon', 'footprint', 'tv', 'presenter', 'matthew', 'bassett', 'shows', 'life', 'goes', 'spinal', 'injury', 'gta', 'rockstar', 'rejected', 'eminem', 'movie', 'deal', 'says', 'insider', 'world', 'cup', '2022', 'frances', 'kylian', 'mbappe', 'upstages', 'olivier', 'giroud', 'goalscoring', 'record', 'mystery', 'deaths', 'two', 'saudi', 'sisters', 'sydney', 'matt', 'hancock', 'celebrity', 'led', 'dozens', 'complaints', 'mps', 'watchdog', 'cricket', 'world', 'cup', 'englandaustralia', 'final', 'shown', 'free', 'air', 'sunday', 'nurses', 'strike', 'thousands', 'join', 'first', 'walkout', 'sad', 'day', 'exeter', 'man', 'held', 'murder', 'woman', 'ludwell', 'valley', 'park', 'tory', 'leadership', 'truss', 'criticised', 'macron', 'jury', 'out', 'remark', 'keir', 'starmer', 'right', 'wages', 'stuck', 'decade', 'were', 'behind', 'you', 'famous', 'faces', 'cheer', 'lionesses', 'zelensky', 'asked', 'give', 'russia', 'part', 'ukraine', 'amber', 'heard', 'easy', 'forget', 'human', 'workers', 'take', 'londons', 'streets', 'amid', 'cost', 'living', 'crisis', 'my', 'cancerous', 'tumour', 'big', 'kettle', 'bell', 'chester', 'zoo', 'rare', 'baby', 'wallaby', 'emerges', 'mothers', 'pouch', 'world', 'cup', '2022', 'belgium', 'afraid', 'lose', 'morocco', 'says', 'roberto', 'martinez', 'boy', 'georges', 'tears', 'hancock', 'enters', 'celeb', 'camp', 'elon', 'musk', 'defends', 'racist', 'tirade', 'dilbert', 'creator', 'scott', 'adams', 'henry', 'cat', 'hearts', 'addenbrookes', 'hospital', 'week', 'pictures', '2', '8', 'april', '2022', 'former', 'uk', 'pm', 'boris', 'johnson', 'makes', 'trip', 'ukraine', 'pictures', 'sporting', 'memories', 'queen', 'cody', 'gakpo', 'liverpool', 'agree', 'sign', 'forward', 'say', 'psv', 'eindhoven', 'prince', 'william', 'oversees', 'trooping', 'colour', 'rehearsal', 'new', 'reality', 'women', 'seeking', 'abortion', 'texas', 'water', 'pipe', 'robots', 'could', 'stop', 'billions', 'litres', 'leaking', 'londons', 'west', 'end', 'man', 'crushed', 'telescopic', 'urinal', 'dies', 'emma', 'raducanu', 'injured', 'british', 'number', 'one', 'faces', 'race', 'fit', 'wimbledon', 'world', 'cup', 'south', 'korea', 'reach', 'last', '16', 'dramatic', 'lastgasp', 'win', 'portugal', 'china', 'spy', 'balloon', 'us', 'navy', 'releases', 'photos', 'debris', 'child', 'q', 'schoolgirl', 'stripsearch', 'isolated', 'issue', 'police', 'data', 'suggests', 'everybody', 'allowed', 'play', 'football', 'liverpool', '33', 'brighton', 'jurgen', 'klopp', 'vows', 'reds', 'fight', 'difficult', 'spell', 'rugby', 'world', 'cup', 'englands', 'claudia', 'macdonald', 'hannah', 'botterman', 'start', 'commonwealth', 'games', 'andrea', 'spendolinisirieix', 'noah', 'williams', 'win', 'mixed', 'synchronised', '10m', 'platform', 'gold', 'suella', 'braverman', 'challenges', 'critics', 'oust', 'asylum', 'row', 'beth', 'mead', 'arsenal', 'forward', 'says', 'record', 'wsl', 'crowd', 'still', 'beginning', 'manchester', 'united', '30', 'sheriff', 'tiraspol', 'cristiano', 'ronaldo', 'scores', 'comfortable', 'win', 't20', 'world', 'cup', 'england', 'v', 'india', 'semifinal', 'jos', 'buttler', 'alex', 'hales', 'star', 'orkney', 'part', 'scallop', 'discos', 'fishing', 'trial', 'putin', 'mariupol', 'russian', 'president', 'saw', 'visit', 'ukraine', 'war', 'jewish', 'children', 'airlifted', 'israel', 'politics', 'increasingly', 'dealbreaker', 'us', 'dating', 'scene', 'covid19', 'china', 'shanghai', 'getting', 'used', 'new', 'normal', 'vietnam', 'veteran', 'wins', 'lottery', 'six', 'times', 'intuition', 'council', 'tax', 'much', 'rising', 'alex', 'murdaugh', 'trial', 'power', 'privilege', 'murder', 'downfall', 'dynasty', 'leicester', 'city', 'boss', 'brendan', 'rodgers', 'vows', 'to', 'fight', 'on', 'survive', 'edgware', 'man', 'arrested', 'woman', 'dies', 'christmas', 'day', 'crash', 'sweden', '50', 'portugal', 'man', 'citys', 'filippa', 'angeldal', 'scores', 'two', 'easy', 'win', 'swedes', 'ukraine', 'war', 'russian', 'foreign', 'minister', 'sergei', 'lavrov', 'factchecked', 'dominic', 'raab', 'faces', 'questions', 'aggressive', 'behaviour', 'claims', 'pakistan', 'floods', 'map', 'beforeafter', 'photos', 'show', 'extent', 'devastation', 'sri', 'lanka', 'protests', 'unifying', 'nation', 'ethnic', 'fault', 'lines', 'run', 'deep', 'us', 'dollar', 'strong', 'mean', 'disabled', 'shropshire', 'man', 'completes', 'sevenday', 'marathon', 'feat', 'charlotszyu', 'undisputed', 'world', 'champion', 'breaks', 'hand', 'leila', 'borrington', 'woman', 'jailed', 'killing', 'threeyearold', 'stepson', 'fa', 'cup', '2023', 'highlights', 'joao', 'palhinha', 'manor', 'solomon', 'score', 'wonder', 'goals', 'fulham', 'beat', 'leeds', 'united', 'alabama', 'hunt', 'missing', 'prison', 'inmate', 'guard', 'billie', 'jean', 'king', 'cup', 'finals', 'great', 'britains', 'underdogs', 'inspired', 'glasgow', 'past', 'experience', 'liverpool', 'boss', 'jurgen', 'klopp', 'says', 'planning', 'fa', 'cup', 'semifinal', 'ridiculous', 'mariupol', 'videos', 'appear', 'show', 'dead', 'civilians', 'us', 'open', 'rory', 'mcilroy', 'englands', 'callum', 'tarren', 'one', 'behind', 'leader', 'adam', 'hadwin', 'mls', 'launches', 'investigation', 'dc', 'united', 'forward', 'taxi', 'fountas', 'accused', 'using', 'racial', 'slur', 'match', 'day', '2', 'analysis', 'bruno', 'guimaraes', 'game', 'newcastle', 'reanne', 'evans', 'beats', 'stuart', 'bingham', 'become', 'first', 'woman', 'win', 'match', 'snooker', 'shoot', 'ukraine', 'conflict', 'growing', 'numbers', 'firms', 'pull', 'back', 'russia', 'oleksiy', 'vadatursky', 'ukraine', 'grain', 'tycoon', 'killed', 'russian', 'shelling', 'mykolaiv', 'tory', 'members', 'vent', 'fury', 'rishi', 'sunaks', 'coronation', 'mps', 'antonio', 'conte', 'italian', 'thanks', 'tottenham', 'fans', 'sharing', 'passion', 'football', 'watch', 'drama', '60', 'seconds', 'corrie', 'mckeague', 'would', 'bingedrink', 'friends', 'death', 'inquest', 'british', 'gymnastics', 'name', 'banned', 'coaches', 'zero', 'tolerance', 'plan', 'abuse', 'strike', 'rules', 'trade', 'union', 'allowed', 'strike', 'commonwealth', 'games', 'englands', 'women', 'beat', 'australia', 'win', 'historic', 'first', 'hockey', 'gold', 'worrying', 'number', 'slim', 'children', 'dieting', 'wallasey', 'pub', 'shooting', 'woman', 'fatally', 'shot', 'targeted', 'police', 'putin', 'sets', 'midnight', 'deadline', 'rouble', 'gas', 'payments', 'big', 'zuu', 'breaking', 'mould', 'cookery', 'shows', 'way

# POS Tagging

In [44]:
nlp = spacy.load('en_core_web_sm')
spacy_doc = nlp(' '.join(tokens_raw_list))


# 1. Faster way: Use a list comprehension to extract data
data = [{'Tokens': token.text, 'POS': token.pos_} for token in spacy_doc]

# 2. Create the DataFrame once
df_pos = pd.DataFrame(data)

# df_pos = pd.DataFrame(columns=['Tokens', 'POS'])

In [45]:
# for tokens in spacy_doc:
#     df_pos = pd.concat([
#         df_pos, pd.DataFrame.from_records([
#             { 'Tokens': tokens.text, 'POS': tokens.pos_}
#         ])
#     ], ignore_index = True)

In [46]:
df_pos_counts = df_pos.groupby(['Tokens','POS']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)

In [47]:
df_pos_counts.head()

     Tokens    POS  counts
95        :  PUNCT     543
8         '  PUNCT     300
2897     in    ADP     187
4082     to   PART     175
3268     of    ADP     172

#### NER tagging

In [54]:
ner_data =  [{'Tokens': token.text, 'NER': token.label_} for token in spacy_doc.ents]
df_ner = pd.DataFrame(ner_data)
df_ner.info()
df_ner.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670 entries, 0 to 1669
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tokens  1670 non-null   object
 1   NER     1670 non-null   object
dtypes: object(2)
memory usage: 26.2+ KB

        Tokens       NER
0    Liz Truss    PERSON
1           UK       GPE
2    Rationing   PRODUCT
3  superyachts  CARDINAL
4      Russian      NORP

In [55]:
df_ner_count = df_ner.groupby(['Tokens','NER']).size().reset_index(name='counts').sort_values(by="counts", ascending=False)
df_ner_count.head()

      Tokens   NER  counts
965  Ukraine   GPE      47
955       UK   GPE      36
329  England   GPE      32
819  Russian  NORP      20
957       US   GPE      19